### ISSUE TITLE
Console error when using `historyRouter` and `link`

### ISSUE THREAD

**Issue by dariooddenino** [arthur-xavier/purescript-react-router#1]
Hi,
I'm setting up a test app but I'm having a problem when using `link`.

These are my update and render functions:

``` purescript
update :: forall props eff. Update State props Action eff
update yield _ action _ _ =
  case action of
    PageView r -> do
      trace "PageView" \_ ->
      yield $ _ { route = r }

render :: forall props. Render State props Action
render dispatch _ state _ =
  div'
    [ historyRouter (dispatch <<< PageView) routes
    , h1' [ link "/" [] [ text "Carpenter Blog" ]]
    , h1' [ link "/posts/1" [] [ text "Post 1" ]]
    , case state.route of
               Home -> p' [ text "Home" ]
               Posts View x -> p' [ text $ "View " <> show x ]
               Posts Edit x -> p' [ text $ "Edit " <> show x ]
    ]
```

If I manually enter the urls, everything works fine. 
If I click on one of the links I get a console error and the page is not updated (the update function is dispatched though).

```
PageView
Uncaught TypeError: f(...) is not a function
    at eval (eval at <anonymous> (http://localhost:3000/main.js:2299:2), <anonymous>:126:16)
    at Object.ReactErrorUtils.invokeGuardedCallback (eval at <anonymous> (http://localhost:3000/main.js:1422:2), <anonymous>:71:16)
    at executeDispatch (eval at <anonymous> (http://localhost:3000/main.js:1788:2), <anonymous>:79:21)
    at Object.executeDispatchesInOrder (eval at <anonymous> (http://localhost:3000/main.js:1788:2), <anonymous>:102:5)
    at executeDispatchesAndRelease (eval at <anonymous> (http://localhost:3000/main.js:948:2), <anonymous>:43:22)
    at executeDispatchesAndReleaseTopLevel (eval at <anonymous> (http://localhost:3000/main.js:948:2), <anonymous>:54:10)
    at Array.forEach (native)
    at forEachAccumulated (eval at <anonymous> (http://localhost:3000/main.js:1482:2), <anonymous>:23:9)
    at Object.processEventQueue (eval at <anonymous> (http://localhost:3000/main.js:948:2), <anonymous>:259:7)
    at runEventQueueInBatch (eval at <anonymous> (http://localhost:3000/main.js:1890:2), <anonymous>:18:18)PageView
Uncaught TypeError: f(...) is not a function
    at eval (eval at <anonymous> (http://localhost:3000/main.js:2299:2), <anonymous>:126:16)
    at Object.ReactErrorUtils.invokeGuardedCallback (eval at <anonymous> (http://localhost:3000/main.js:1422:2), <anonymous>:71:16)
    at executeDispatch (eval at <anonymous> (http://localhost:3000/main.js:1788:2), <anonymous>:79:21)
    at Object.executeDispatchesInOrder (eval at <anonymous> (http://localhost:3000/main.js:1788:2), <anonymous>:102:5)
    at executeDispatchesAndRelease (eval at <anonymous> (http://localhost:3000/main.js:948:2), <anonymous>:43:22)
    at executeDispatchesAndReleaseTopLevel (eval at <anonymous> (http://localhost:3000/main.js:948:2), <anonymous>:54:10)
    at Array.forEach (native)
    at forEachAccumulated (eval at <anonymous> (http://localhost:3000/main.js:1482:2), <anonymous>:23:9)
    at Object.processEventQueue (eval at <anonymous> (http://localhost:3000/main.js:948:2), <anonymous>:259:7)
    at runEventQueueInBatch (eval at <anonymous> (http://localhost:3000/main.js:1890:2), <anonymous>:18:18)
```

**Comment by arthurxavierx** [comment]
Hi @dariooddenino, have you updated to the latest version `0.2.1`? This bug happened in `0.2.0`. I believe this was already fixed.

**Comment by dariooddenino** [comment]
Hi! Yes, I'm using `0.2.1`

**Comment by arthurxavierx** [comment]
Going to check it then. Just another assurance, have you tried cleaning up `output` and `pulp build` everything?

**Comment by dariooddenino** [comment]
After cleaning up and rebuilding I still get the same error

**Comment by arthurxavierx** [comment]
It was indeed happening. I'm still making some mistakes when using `Eff` with the FFI.
Please check if `0.2.2` fixes it for you. Fixed for me.

**Comment by dariooddenino** [comment]
Works perfectly now, thanks! :)
